name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: 📚 Documentation
    labels:
      - documentation
    collapse-after: 10
  - title: "🧰 Maintenance"
    labels:
      - chore
      - maintenance
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 10
  - title: "📋 Markdown Templates"
    labels:
      - "markdown-templates"
  - title: "⚙️ Reusable Workflows"
    labels:
      - "reusable-workflows"
  - title: ✍ Other changes

# Automatically add labels based on file paths
autolabeler:
  - label: "reusable-workflows"
    files:
      - ".github/workflows/*.yml"
      - ".github/workflows/[!_]*.yaml"
  - label: "markdown-templates"
    files:
      - "templates/**.md"
  - label: "documentation"
    files:
      - "docs/**/*"
      - "*.md"

template: |
  ## What's Changed in v$RESOLVED_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Contributors

  $CONTRIBUTORS
