name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: "📋 Markdown Templates"
    labels:
      - "templates"
  - title: "⚙️ Reusable Workflows"
    labels:
      - "workflows"
  - title: 📚 Documentation
    labels:
      - documentation
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 10
  - title: ✍ Other changes


# Automatically add labels based on file paths
autolabeler:
  - label: "workflows"
    files:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  - label: "templates"
    files:
      - "templates/**.md"
  - label: "documentation"
    files:
      - "docs/**/*"
      - "*.md"


template: |
  ## What's Changed in v$RESOLVED_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  **Contributors**: $CONTRIBUTORS
