name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
    pull-requests: write # to add label to PR (release-drafter/release-drafter)
    contents: write # to create a github release (release-drafter/release-drafter)
    
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
