name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
