name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

  # pull_request event is required for autolabeler
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions:
  pull-requests: write # to add label to PR
  contents: write # to create a github release

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
